### ISSUE TITLE
Use is-string-blank

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/fast-isnumeric#2]
🌴 We should use the new https://github.com/plotly/is-string-blank here (and propagate this to plotly.js)
cc @archmoj

**Comment by archmoj** [comment]
@etpinard we need Github (& possibly NPM) permissions to push to this repository. 
Thanks.

**Comment by etpinard** [comment]
done and done :ok_hand:

**Comment by archmoj** [comment]
I still get this error: `Permission to plotly/fast-isnumeric.git denied to archmoj.`

**Comment by etpinard** [comment]
My bad, Try again.

**Comment by archmoj** [comment]
Now it finally worked! Thank you @etpinard .
